name: login_authentcation
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  image_picker: ^1.0.8
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  tflite_flutter: ^0.10.4
  google_sign_in: ^6.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # Add this package

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Change this path to your app icon file
  adaptive_icon_background: "#ffffff" # Optional for Android adaptive icons

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/best_pcos_model.tflite
